export const Logo = require('./Logo.png'); // Main logo image
export const Logo2 = require('./Logo2.png'); // Alternate logo image
export const Banner = require('./Bannar.png'); // Banner image 1
export const Banner1 = require('./Bannar1.png'); // Banner image 2
export const Banner2 = require('./Bannar2.png'); // Banner image 3
export const Banner3 = require('./Bannar3.png'); // Banner image 4
export const Desktop = require('./Desktop - 11.png'); // Desktop image
export const Bg1 = require('./Group 237574.png'); // Background image 1
export const Girl = require('./image 3.png'); // Girl image
export const Guy = require('./image 4.png'); // Guy image
export const Picture = require('./Picture.png'); // Picture image 1
export const Picture1 = require('./Picture1.png'); // Picture image 2
export const Picture2 = require('./Picture2.png'); // Picture image 3
export const Icon = require('./Icon.png'); // Icon image 1
export const Icon1 = require('./Icon1.png'); // Icon image 2
export const Icon2 = require('./icon2.png'); // Icon image 3
export const Icon3 = require('./Icon3.png'); // Icon image 4
export const Special = require('./Special.png'); // Special image 1
export const Special1 = require('./Special1.png'); // Special image 2
export const Special2 = require('./Special2.png'); // Special image 3
export const Brand = require('./brand.png'); // Brand image 1
export const Brand1 = require('./mango-1.png'); // Brand image 2
export const Brand2 = require('./brand2.png'); // Brand image 3
export const Brand3 = require('./food.png'); // Brand image 4
export const Brand4 = require('./bookoff-corporation-logo.png'); // Brand image 5
export const Brand5 = require('./brand5.png'); // Brand image 6
export const Men = require('./6db2b1b376 1.png'); // Men image
export const SideImage = require('./SideImage.png'); // Side image
export const ApplePay = require('./ApplePay.png'); // Side image
export const Cart = require('./Cart.png'); // Side image
export const Discover = require('./Discover.png'); // Side image
export const Mastercard = require('./Mastercard.png'); // Side image
export const Visa = require('./Visa.png'); // Side image
export const Logos = require ('./Frame 427319018.png'); 
export const GroupMen = require ('./Group Men.png'); 
export const Couple = require ('./couple.png'); 